language: java
jdk:
- openjdk8
script: mvn clean package
notifications:
  slack:
    secure: g8hSV4aE5qv43HYKBgLh7e9aoEz8/+mMCNurRUnA7KyK3J8/LjOrUvG1Dbmd2dLyTTL8UG7AALEofVXpu8HiuDYKjoUfiKw8NV6qGHzArVbG0N3y4Qmd58u4uCR4BOBXbtA5D2aWzdbWLQ8fiA3dAs1njID6z6SxB64FqjFRXEEJKc2f/IhtGkjGMMmFhtzJOUEGuAqcLJdLw1QacR/WOkTe7KNh2dngm3GBYDxptIz0pPfiFjxyDeklhE2o/sp1f+HUmSoPjHgSzTPuhPEZNS6SMCBlpGiwy3vGB9/KH6g0nIbYFJdSLJFK3v+rGx9pd2broVjzxNZCNnrSiHpQwe05B2tAZGA/roNYXROB/jFfMx0oqwuBTc00U3XOpbnyQPb+e3VTGsFuSxzacy3Fj9Y9I11hUK/3gwtSTovHFw/Fnp6m04njVgqMldtrV9i3SLZBqPIfY45a9mqeENLWrn4CieQ7SvKos4Sl0ci/l1HN8g8W4t2wYzOrR5RuJ9ZtQbR6jsD7gSH9cZCdQjFV6KIkY0GyQR/rYTerGcP+/dOAc3N/zU5I4Q2hZPQFd/2L22MipSqAB1aNUeJ2+T3U6XW951CRPtK49n9p/RX1AjITtnz9RZ+2h61D/IR/HtfDIMXc2Tbn8dyMKQMdj73XfSgQXsYLpm0LlaE8xd76yJI=
